### ISSUE TITLE
Переехать в инкубатор

### ISSUE THREAD

**Issue by voischev** [bem-incubator/bem-social#56]

**Comment by blond** [comment]
:+1:

**Comment by voischev** [comment]
@tadatuta дай права. Не могу переехать

**Comment by tadatuta** [comment]
@voischev отправил инвайт

**Comment by voischev** [comment]
@tadatuta спасибо. Все получилось

**Comment by zxqfox** [comment]
@voischev Лучше в этой же задачи все ссылки поменять и пр.
