### ISSUE TITLE
add bh templates

### ISSUE THREAD

**Issue by sameoldmadness** [bem-incubator/bem-social#59]
to become compatible with bem-components

**Comment by voischev** [comment]
@zxqfox Будет время посмотришь?

**Comment by zxqfox** [comment]
@voischev yeah, np.

**Comment by kompolom** [comment]
@zxqfox не начинал  с bh?

**Comment by zxqfox** [comment]
@kompolom Думаю, завтра займусь. Если хочешь сделать — забирай ;-)

**Comment by kompolom** [comment]
у меня только после выходных время появится. Если что то останется - возьму.

**Comment by zxqfox** [comment]
типа, все.
