### ISSUE TITLE
Документация по установке

### ISSUE THREAD

**Issue by kompolom** [bem-incubator/bem-social#60]
Было бы здорово добавить в документацию, раздел "установка". скопипастил себе код в `bower.json` - и сидишь, радуешься ))

**Comment by voischev** [comment]
Немного не понял) Можешь привести пример такой документации?

**Comment by kompolom** [comment]
"Документация"  громко сказано, конечно. Раздел в readme.  
https://github.com/bem-incubator/bem-grid#install

**Comment by voischev** [comment]
@kompolom посмотри все ли понятно? #67

**Comment by kompolom** [comment]
:thumbsup:
